import React from 'react';
import { Message, Role } from '../types';
import { FileText, Printer, X } from 'lucide-react';
import { MarkdownRenderer } from '../utils/markdown';

interface LabReportViewProps {
    title: string;
    messages: Message[];
    onClose: () => void;
}

export const LabReportView: React.FC<LabReportViewProps> = ({ title, messages, onClose }) => {
    
    // Filter mainly model messages that contain scientific content
    const reportContent = messages.filter(m => m.text.length > 50 || m.attachments?.length);
    
    const handlePrint = () => {
        window.print();
    };

    return (
        <div className="fixed inset-0 z-50 bg-gray-900/50 backdrop-blur-sm flex items-center justify-center p-4">
            <div className="bg-white w-full max-w-4xl h-[90vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden">
                {/* Header (No Print) */}
                <div className="flex items-center justify-between p-4 border-b border-gray-200 bg-gray-50 print:hidden">
                    <div className="flex items-center gap-3">
                        <div className="p-2 bg-green-100 rounded-lg text-green-700">
                            <FileText size={20} />
                        </div>
                        <div>
                            <h2 className="font-bold text-gray-900">Lab Report Preview</h2>
                            <p className="text-xs text-gray-500">Ready for export</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                         <button 
                            onClick={handlePrint}
                            className="flex items-center gap-2 px-4 py-2 bg-gray-900 text-white rounded-lg hover:bg-gray-800 text-sm font-medium transition-colors"
                        >
                            <Printer size={16} />
                            Print / Save PDF
                        </button>
                        <button 
                            onClick={onClose}
                            className="p-2 text-gray-500 hover:bg-gray-200 rounded-lg transition-colors"
                        >
                            <X size={20} />
                        </button>
                    </div>
                </div>

                {/* Printable Content */}
                <div className="flex-1 overflow-y-auto p-8 md:p-12 bg-white print:p-0 print:overflow-visible">
                    <div className="max-w-3xl mx-auto space-y-6 print:space-y-4">
                        
                        <div className="border-b-2 border-black pb-4 mb-8">
                            <h1 className="text-3xl font-serif font-bold text-gray-900 mb-2">{title}</h1>
                            <div className="flex justify-between text-sm text-gray-600 font-serif">
                                <span>Generated by EcoSci AI</span>
                                <span>{new Date().toLocaleDateString()}</span>
                            </div>
                        </div>

                        {reportContent.map((msg, idx) => (
                            <div key={idx} className={`mb-6 ${msg.role === Role.USER ? 'bg-gray-50 p-4 rounded border-l-4 border-gray-300 print:bg-transparent print:border-gray-200' : ''}`}>
                                {msg.role === Role.USER && (
                                    <h4 className="text-xs font-bold uppercase text-gray-500 mb-2 tracking-wider">Observation Note</h4>
                                )}
                                
                                {msg.attachments && msg.attachments.length > 0 && (
                                    <div className="flex gap-4 mb-4">
                                        {msg.attachments.map((att, i) => (
                                            <img 
                                                key={i} 
                                                src={`data:${att.mimeType};base64,${att.data}`} 
                                                className="h-48 w-auto object-contain border border-gray-200 rounded bg-white"
                                                alt="Specimen"
                                            />
                                        ))}
                                    </div>
                                )}
                                
                                <div className="prose prose-sm max-w-none text-gray-900 font-serif leading-relaxed">
                                    <MarkdownRenderer content={msg.text} />
                                </div>
                            </div>
                        ))}
                        
                        <div className="mt-12 pt-8 border-t border-gray-200 text-center text-xs text-gray-400 font-sans print:fixed print:bottom-4 print:left-0 print:w-full">
                            Report generated via EcoSci Educational Platform. Valid for academic portfolio use.
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};